const playerData = [
    {
      setName: "SET 1 M1",
      players: [
        { name: "Virat Kohli", basePrice: "2cr", type:"bat",  src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/2.png" },
        { name: "Rajat Patidar", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/597.png" },
        { name: "Suryakumar Yadav", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/174.png" },
        { name: "Rohit Sharma", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/6.png" },
        { name: "Henrich Klassen ✈️", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/202.png" },
        { name: "Travis Head ✈️", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/37.png" },
      ],
    },
    {
      setName: "SET 2 M2",
      players: [
        { name: "Ruturaj Gaikwad", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/102.png" },
        { name: "MS Dhoni", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/57.png" },
        { name: "Tristan Stubbs ✈️", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1017.png" },
        { name: "Abhishek Porel", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1580.png" },
        { name: "Rinku Singh", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/152.png" },
        { name: "Sanju Samson", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/190.png" },
      ],
    },
    {
      setName: "SET 3 M3",
      players: [
        { name: "Dhruv Jurel", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1004.png" },
        { name: "Shimron Hetmyer ✈️", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/210.png" },
        { name: "Shubman Gill", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/62.png" },
        { name: "Nicholas Pooran ✈️", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/136.png" },
        { name: "Prabhsimran Singh", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/137.png" },
        { name: "Hardik Pandya", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/54.png" },
      ],
    },
    {
      setName: "SET 4 M4",
      players: [
        { name: "Tilak Varma", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/993.png" },
        { name: "Pat Cummins ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/33.png" },
        { name: "Abhishek Sharma", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/212.png" },
        { name: "N K Reddy", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1944.png" },
        { name: "Ravindra Jadeja", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/46.png" },
        { name: "Shivam Dube", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/211.png" },
      ],
    },
    {
      setName: "SET 5 M5",
      players: [
        { name: "Axar Patel", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/110.png" },
        { name: "Varun Ch.", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/140.png" },
        { name: "Andre Russell ✈️", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/141.png" },
        { name: "Ramandeep Singh", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/991.png" },
        { name: "Yashasvi Jaiswal", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/533.png" },
        { name: "Riyan Parag", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/189.png" },
      ],
    },
    {
      setName: "SET 6 M6",
      players: [
        { name: "Sai Sudharshan", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/976.png" },
        { name: "Rahul Tewatia", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/120.png" },
        { name: "Shahrukh Khan", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/590.png" },
        { name: "Ayush Badoni", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/985.png" },
        { name: "Shashank Singh", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/191.png" },
        { name: "Yash Dayal", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/978.png" },
      ],
    },
    {
      setName: "SET 7 M7",
      players: [
        { name: "Jasprit Bumrah", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/9.png" },
        { name: "M Pathirana ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1014.png" },
        { name: "Kuldeep yadav", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/14.png" },
        { name: "Sunil Narine ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/156.png" },
        { name: "Harshit Rana", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1013.png" },
        { name: "Sandeep Sharma", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/220.png" },
      ],
    },
    {
      setName: "SET 8 M8",
      players: [
        { name: "Rashid khan ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/218.png" },
        { name: "ravi Bishnoi", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/520.png" },
        { name: "Mayank Yadav", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/987.png" },
        { name: "Mohsin khan", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/541.png" },
      ],
    },
    {
      setName: "SET 9 M9",
      players: [
        { name: "jos Buttler ✈️", basePrice: "2cr", type:"wk", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/509.png" },
        { name: "shreyas Iyer", basePrice: "2cr", type:"bat", src:"https://www.kkr.in/static-assets/images/players/63961.png?v=111.56" },
        { name: "rishabh Pant", basePrice: "2cr", type:"wk", src:"https://cricclubs.com/documentsRep/profilePics/1a3a0ae3-1d08-4717-9b49-b82dfc32c5c8.jpeg" },
        { name: "kagiso Rabada ✈️", basePrice: "2cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/63611.png?v=5.12" },
        { name: "Arshdeep Singh", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/125.png" },
        { name: "mitchell Starc ✈️", basePrice: "2cr", type:"bowl", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/10053.png?v=1.62" },
      ],
    },
    {
      setName: "SET 10 M10",
      players: [
        { name: "yuzvendra Chahal", basePrice: "2cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/9844.png?v=6.73" },
        { name: "liam Livingstone ✈️", basePrice: "2cr", type:"al", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/Liam.png?itok=vgVq3IRv" },
        { name: "david Miller ✈️", basePrice: "1.5cr", type:"bat", src:"https://www.gujarattitansipl.com/static-assets/images/players/5313.png?v=5.12" },
        { name: "kl Rahul", basePrice: "2cr", type:"wk", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/60122.png?v=1.62" },
        { name: "Mohammad Shami", basePrice: "2cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/28994.png?v=5.12" },
        { name: "Mohammad Siraj", basePrice: "2cr", type:"bowl", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/3840.png" },
      ],
    },
    {
      setName: "SET 11 BA1",
      players: [
        { name: "harry Brook ✈️", basePrice: "2cr", type:"bat", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/66374.png?v=1.62" },
        { name: "devon Conway ✈️", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/601.png" },
        { name: "jake f-mcgurk ✈️", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/3115.png" },
        { name: "aiden Markram ✈️", basePrice: "2cr", type:"bat", src:"https://www.lucknowsupergiants.in/static-assets/images/players/64219.png?v=12.55" },
        { name: "devdutt Padikkal", basePrice: "2cr", type:"bat", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/DDp.png?itok=2Z6Kz01S" },
        { name: "rahul Tripathi", basePrice: "0.75cr", type:"bat", src:"https://documents.iplt20.com/playerheadshot/ipl/284/3838.png" },
        { name: "david Warner ✈️", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/214.png" },
      ],
    },
    {
      setName: "SET 12 AL1",
      players: [
        { name: "r Ashwin", basePrice: "2cr", type:"al", src:"https://www.rajasthanroyals.com/static-assets/images/players/4555.png?v=6.73" },
        { name: "Venkatesh Iyer", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/584.png" },
        { name: "mitchell Marsh ✈️", basePrice: "2cr", type:"al", src:"https://www.lucknowsupergiants.in/static-assets/images/players/10094.png?v=12.55" },
        { name: "glenn Maxwell ✈️", basePrice: "2cr", type:"al", src:"https://www.punjabkingsipl.in/static-assets/images/players/10085.png?v=6.16" },
        { name: "Harshal patel", basePrice: "2cr", type:"al", src:"https://www.punjabkingsipl.in/static-assets/images/players/5407.png?v=6.16" },
        { name: "Rachin Ravindra ✈️", basePrice: "1.5cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/724.png" },
        { name: "marcus Stoinis ✈️", basePrice: "2cr", type:"al", src:"https://www.punjabkingsipl.in/static-assets/images/players/4311.png?v=6.16" },
      ],
    },
  
    {
      setName: "SET 13 WK1",
      players: [
        { name: "jonny Bairstow ✈️", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/216.png" },
        { name: "quinton DeKock ✈️", basePrice: "2cr", type:"wk", src:"https://www.kkr.in/static-assets/images/players/28035.png?v=111.56" },
        { name: "R Gurbaz ✈️", basePrice: "2cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/641.png" },
        { name: "Ishan kishan", basePrice: "2cr", type:"wk", src:"https://www.bdcrictime.com/_next/image?url=https%3A%2F%2Fapi.bdcrictime.com%2FProfile%2Fishan-kishan-13_10_2023.jpg&w=384&q=75" },
        { name: "phil Salt ✈️", basePrice: "2cr", type:"wk", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/salt%20%281%29.png?itok=_gBRI7Y4" },
        { name: "Jitesh Sharma", basePrice: "1cr", type:"wk", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/jitesh.png?itok=QM393_-r" },
      ],
    },
    {
      setName: "SET 14 FA1",
      players: [
        { name: "Khaleel ahmed", basePrice: "2cr", type:"bowl", src:"https://static.cricketaddictor.com/images/team/khaleel-ahmed.png?q=80" },
        { name: "trent Boult ✈️", basePrice: "2cr", type:"bowl", src:"https://www.mumbaiindians.com/static-assets/images/players/large/4338.png?v=4.49&w=200" },
        { name: "josh Hazlewood ✈️", basePrice: "2cr", type:"bowl", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/josh_0.png?itok=Z5DZxC2-" },
        { name: "Avesh khan", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/109.png" },
        { name: "Prasidh krishna", basePrice: "2cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/65702.png?v=5.12" },
        { name: "T Natrajan", basePrice: "2cr", type:"bowl", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/65160.png?v=1.62" },
        { name: "anrich Nortje ✈️", basePrice: "2cr", type:"bowl", src:"https://www.kkr.in/static-assets/images/players/63641.png?v=111.56" },
        { name: "jofra Archer ✈️", basePrice: "2cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/64254.png?v=6.73" },
      ],
    },
    {
      setName: "SET 15 SP1",
      players: [
        { name: "Noor ahmed ✈️", basePrice: "2cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/71411.png?v=5.12" },
        { name: "Rahul Chahar", basePrice: "1cr", type:"bowl", src:"https://www.punjabkingsipl.in/static-assets/images/players/66823.png?v=6.16" },
        { name: "W Hasaranga ✈️", basePrice: "2cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/65027.png?v=6.73" },
        { name: "Waqar ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.lakriders.us/static-assets/images/players/67943.png?v=1.27" },
        { name: "M Theekshana ✈️", basePrice: "2cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/69274.png?v=6.73" },
        { name: "adam Zampa ✈️", basePrice: "2cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/58913.png?v=6.73" },
      ],
    },
    {
      setName: "SET 16 UBA1",
      players: [
        { name: "Yash Dhull", basePrice: "0.3cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/777.png" },
        { name: "Abhinav Manohar", basePrice: "0.3cr", type:"bat", src:"https://www.gujarattitansipl.com/static-assets/images/players/63715.png?v=5.12" },
        { name: "Karun Nair", basePrice: "0.3cr", type:"bat", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/62297.png?v=1.62" },
        { name: "Raghuvanshi", basePrice: "0.3cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/787.png" },
        { name: "Anmolpreet", basePrice: "0.3cr", type:"bat", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/2965.png" },
        { name: "Atharva Taide", basePrice: "0.3cr", type:"bat", src:"https://www.punjabkingsipl.in/static-assets/images/players/67910.png?v=6.16" },
        { name: "Nehal Wadhera", basePrice: "0.3cr", type:"bat", src:"https://www.punjabkingsipl.in/static-assets/images/players/69657.png?v=6.16" },
      ],
    },
    {
      setName: "SET 17 UAL1",
      players: [
        { name: "H Brar", basePrice: "0.3cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/130.png" },
        { name: "Naman dhir", basePrice: "0.3cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/3107.png" },
        { name: "mahipal Lomror", basePrice: "0.5cr", type:"al", src:"https://www.gujarattitansipl.com/static-assets/images/players/65432.png?v=5.12" },
        { name: "Sameer Rizwi", basePrice: "0.3cr", type:"al", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/71376.png?v=1.62" },
        { name: "Abdul Samad", basePrice: "0.3cr", type:"al", src:"https://www.lucknowsupergiants.in/static-assets/images/players/71260.png?v=12.55" },
        { name: "Vijay Shankar", basePrice: "0.3cr", type:"al", src:"https://www.gujarattitansipl.com/static-assets/images/players/61738.png?v=5.12" },
        { name: "Ashutosh sharma", basePrice: "0.3cr", type:"al", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/68176.png?v=1.62" },
      ],
    },
    {
      setName: "SET 18 UWK1",
      players: [
        { name: "Kumar Kushagra", basePrice: "0.3cr", type:"wk", src:"https://cricclubs.com/documentsRep/profilePics/cb4ed029-2e2f-4465-8744-06d0554ff757.jpeg" },
        { name: "Robin Minz", basePrice: "0.3cr", type:"wk", src:"https://www.mumbaiindians.com/static-assets/images/players/large/95322.png?v=4.49&w=200" },
        { name: "anuj Rawat", basePrice: "0.3cr", type:"wk", src:"https://cricclubs.com/documentsRep/profilePics/18c9f8a4-0ea0-4cd3-89c8-aaabe87994d0.jpeg" },
        { name: "Vishnu Vinod", basePrice: "0.3cr", type:"wk", src:"https://www.punjabkingsipl.in/static-assets/images/players/64783.png?v=6.16" },
        { name: "Upendra Yadav", basePrice: "0.3cr", type:"wk", src:"https://ipltable.in/wp-content/uploads/2024/03/image-40.jpeg" },
      ],
    },
    {
      setName: "SET 19 UFA1",
      players: [
        { name: "Vaibhav Arora", basePrice: "0.3cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/583.png" },
        { name: "Rashik Dar", basePrice: "0.3cr", type:"bowl", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/20577.png" },
        { name: "Akash Madhwal", basePrice: "0.3cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/74055.png?v=6.73" },
        { name: "Mohit Sharma", basePrice: "0.5cr", type:"bowl", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/63341.png?v=1.62" },
        { name: "Simarjeet Singh", basePrice: "0.3cr", type:"bowl", src:"https://cricclubs.com/documentsRep/profilePics/ee6c74d6-8507-404e-8f09-42abdbb5cd56.jpeg" },
        { name: "Yash Thakur", basePrice: "0.3cr", type:"bowl", src:"https://www.punjabkingsipl.in/static-assets/images/players/66819.png?v=6.16" },
        { name: "Kartik Tyagi", basePrice: "0.4cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/536.png" },
        { name: "Vyshak Vijaykumar", basePrice: "0.3cr", type:"bowl", src:"https://www.punjabkingsipl.in/static-assets/images/players/67628.png?v=6.16" },
      ],
    },
    {
      setName: "SET 20 USP1",
      players: [
        { name: "Piyush Chawla", basePrice: "0.5cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/149.png" },
        { name: "Shreyas Gopal", basePrice: "0.3cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/192.png" },
        { name: "Mayank Markande", basePrice: "0.3cr", type:"bowl", src:"https://www.kkr.in/static-assets/images/players/67126.png?v=111.56" },
        { name: "Suyash Sharma", basePrice: "0.3cr", type:"bowl", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/suyash%20sharma%20%281%29.png?itok=WMbwjG_p" },
        { name: "Karn Sharma", basePrice: "0.5cr", type:"bowl", src:"https://www.mumbaiindians.com/static-assets/images/players/large/5090.png?v=4.49&w=200" },
        { name: "Kumar Kartikeya", basePrice: "0.3cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/70191.png?v=6.73" },
        { name: "Manav Suthar", basePrice: "0.3cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/2443.png" },
      ],
    },
    {
      setName: "SET 21 BA2",
      players: [
        { name: "Mayank Agarwal", basePrice: "1cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/55.png" },
        { name: "Faf du plessis ✈️", basePrice: "2cr", type:"bat", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/28891.png?v=1.62" },
        { name: "glenn Phillips ✈️", basePrice: "2cr", type:"bat", src:"https://www.gujarattitansipl.com/static-assets/images/players/65295.png?v=5.12" },
        { name: "rovman Powell ✈️", basePrice: "1.5cr", type:"bat", src:"https://www.kkr.in/static-assets/images/players/65291.png?v=111.56" },
        { name: "ajinkya Rahane", basePrice: "1.5cr", type:"bat", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/135.png" },
        { name: "prithwi Shaw", basePrice: "0.75cr", type:"bat", src:"https://preview.redd.it/ipl-2024-delhi-capitals-retain-prithvi-shaw-v0-8g1pxxkz5j2c1.png?auto=webp&s=2e34f43423e9032f4f3de96b17e511bb2b37e6f4" },
        { name: "kane Williamson ✈️", basePrice: "2cr", type:"bat", src:"https://www.gujarattitansipl.com/static-assets/images/players/4330.png?v=5.12" },
      ],
    },
  
    {
      setName: "SET 22 AL2",
      players: [
        { name: "sam Curran ✈️", basePrice: "2cr", type:"al", src:"https://www.punjabkingsipl.in/static-assets/images/players/65584.png?v=6.16" },
        { name: "marco Jansen ✈️", basePrice: "1.25cr", type:"al", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/17068.png" },
        { name: "Daryl Mitchell ✈️", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/83.png" },
        { name: "Krunal Pandya", basePrice: "2cr", type:"al", src:"https://www.lucknowsupergiants.in/static-assets/images/players/63788.png?v=12.55" },
        { name: "Nitish Rana", basePrice: "1.5cr", type:"al", src:"https://www.rajasthanroyals.com/static-assets/images/players/63649.png?v=6.73" },
        { name: "w Sundar", basePrice: "2cr", type:"al", src:"https://www.gujarattitansipl.com/static-assets/images/players/65859.png?v=5.12" },
        { name: "Shardul Thakur", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/105.png" },
      ],
    },
    {
      setName: "SET 23 WK2",
      players: [
        { name: "alex Carey ✈️", basePrice: "1cr", type:"wk", src:"https://documents.iplt20.com/playerheadshot/ipl/284/3882.png" },
        { name: "KS Bharat", basePrice: "0.75cr", type:"wk", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/2734.png" },
        { name: "D Ferreira✈️", basePrice: "0.75cr", type:"wk", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/23487.png?v=1.62" },
        { name: "Shai Hope ✈️", basePrice: "1.25cr", type:"wk", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/268.png" },
        { name: "josh Inglis ✈️", basePrice: "2cr", type:"wk", src:"https://www.punjabkingsipl.in/static-assets/images/players/65893.png?v=6.16" },
        { name: "Ryan Rickelton ✈️", basePrice: "1cr", type:"wk", src:"https://www.mumbaiindians.com/static-assets/images/players/large/64941.png?v=4.49&w=200" },
      ],
    },
    {
      setName: "SET 24 FA2",
      players: [
        { name: "Deepak Chahar", basePrice: "2cr", type:"bowl", src:"https://www.mumbaiindians.com/static-assets/images/players/large/59547.png?v=4.49&w=200" },
        { name: "gerald Coeetze ✈️", basePrice: "1.25cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/67443.png?v=5.12" },
        { name: "Akash Deep", basePrice: "1cr", type:"bowl", src:"https://www.lucknowsupergiants.in/static-assets/images/players/71447.png?v=12.55" },
        { name: "Tushar Deshpande", basePrice: "1cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/65478.png?v=6.73" },
        { name: "lokie Ferguson ✈️", basePrice: "2cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/63719.png?v=5.12" },
        { name: "Bhuvneshwar kumar", basePrice: "2cr", type:"bowl", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/bhuvi%20%281%29.png?itok=YJy5hWNo" },
        { name: "Mukesh Kumar", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1462.png" },
      ],
    },
    {
      setName: "SET 25 SP2",
      players: [
        { name: "Akeal Hosein ✈️", basePrice: "1.5cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/722.png" },
        { name: "Keshav Maharaj ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/48607.png?v=6.73" },
        { name: "Mujeeb Ur Rahman ✈️", basePrice: "2cr", type:"bowl", src:"https://i.cdn.newsbytesapp.com/sports/players/profile/mujeeb-ur-rahman.png" },
        { name: "Adil Rashid ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/311.png" },
        { name: "Tabraiz Shamsi ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/playerheadshot/ipl/284/3309.png" },
      ],
    },
    {
      setName: "SET 26 UBA2",
      players: [
        { name: "Ricky Bhui", basePrice: "0.3cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/219.png" },
        { name: "Swastik Chhikara", basePrice: "0.3cr", type:"bat", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/schik.png?itok=ItexPUtY" },
        { name: "Shubham Dubey", basePrice: "0.3cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/3112.png" },
        { name: "Shaik Rasheed", basePrice: "0.3cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/778.png" },
      ],
    },
    {
      setName: "SET 27 UAL2",
      players: [
        { name: "Mayank Dagar", basePrice: "0.3cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1547.png" },
        { name: "Anshul Kamboj", basePrice: "0.3cr", type:"al", src:"https://cricclubs.com/documentsRep/profilePics/4a1091fb-cf73-45d0-9152-c8bd44bf39cd.jpeg" },
        { name: "Md. Arshad Khan", basePrice: "0.3cr", type:"al", src:"https://www.gujarattitansipl.com/static-assets/images/players/82839.png?v=5.12" },
        { name: "S Prabhudessai", basePrice: "0.3cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/598.png" },
        { name: "Anukul Roy", basePrice: "0.3cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/160.png" },
        { name: "Swapnil Singh", basePrice: "0.3cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/1483.png" },
      ],
    },
    {
      setName: "SET 28 BA3",
      players: [
        { name: "Finn Allen ✈️", basePrice: "2cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/595.png" },
        { name: "D Brevis ✈️", basePrice: "0.75cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/797.png" },
        { name: "Ben Duckett ✈️", basePrice: "2cr", type:"bat", src:"https://images-cricketcom.imgix.net/players/63082_headshot_safari.png?auto=format,compress" },
        { name: "Manish Pandey", basePrice: "0.75cr", type:"bat", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/16.png" },
        { name: "Rilee Rossow ✈️", basePrice: "2cr", type:"bat", src:"https://www.lakriders.us/static-assets/images/players/4357.png?v=1.27" },
        { name: "Sherfane Rutherford ✈️", basePrice: "1.5cr", type:"bat", src:"https://www.gujarattitansipl.com/static-assets/images/players/67285.png?v=5.12" },
      ],
    },
    {
      setName: "SET 29 AL3",
      players: [
        { name: "Shahbaz Ahmed", basePrice: "1cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/523.png" },
        { name: "Moeen Ali ✈️", basePrice: "2cr", type:"al", src:"https://www.kkr.in/static-assets/images/players/4688.png?v=111.56" },
        { name: "Tim David ✈️", basePrice: "2cr", type:"al", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/Tim.png?itok=GHNNHK51" },
        { name: "Deepak Hooda", basePrice: "0.75cr", type:"al", src:"https://www.lucknowsupergiants.in/static-assets/images/players/63748.png?v=12.55" },
        { name: "Will Jacks ✈️", basePrice: "2cr", type:"al", src:"https://www.mumbaiindians.com/static-assets/images/players/large/66927.png?v=4.49&w=200" },
        { name: "A Omarzai ✈️", basePrice: "1.5cr", type:"al", src:"https://www.gujarattitansipl.com/static-assets/images/players/67516.png?v=5.12" },
        { name: "Sai Kishore", basePrice: "0.75cr", type:"al", src:"https://static.cricketaddictor.com/images/team/ravisrinivasan-sai-kishore.png?q=80" },
        { name: "R Shepherd ✈️", basePrice: "1.5cr", type:"al", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/romario%20shephard%20%281%29.png?itok=_dKvCqNq" },
      ],
    },
    {
      setName: "SET 30 FA3",
      players: [
        { name: "Nandre Burger ✈️", basePrice: "1.25cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/66195.png?v=6.73" },
        { name: "Spencer Johnson ✈️", basePrice: "2cr", type:"bowl", src:"https://www.kkr.in/static-assets/images/players/67778.png?v=111.56" },
        { name: "Umran Malik", basePrice: "0.75cr", type:"bowl", src:"https://www.kkr.in/static-assets/images/players/82969.png?v=111.56" },
        { name: "M Rahman ✈️", basePrice: "2cr", type:"bowl", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/1594.png" },
        { name: "Ishant Sharma", basePrice: "0.75cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/3899.png?v=5.12" },
        { name: "Nuwan Tushara ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/Nuwan%20Thushara%20%281%29.png?itok=NAx2Sw-p" },
        { name: "Naveen Ul Haq ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/639.png" },
        { name: "Jaydev Unadkat", basePrice: "1cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/180.png" },
        { name: "Umesh Yadav", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/21.png" },
      ],
    },
    {
      setName: "SET 31 BA4",
      players: [
        { name: "Mark Chapman ✈️", basePrice: "1.5cr", type:"bat", src:"https://www.hindustantimes.com/static-content/1y/cricket-logos/players/mark-chapman.png" },
        { name: "Brandon King ✈️", basePrice: "0.75cr", type:"bat", src:"https://i2.wp.com/crictoday.com/wp-content/uploads/2023/06/stream-2023-06-08T170345.596.jpg?strip=info&w=640&ssl=1" },
        { name: "Evin Lewis ✈️", basePrice: "2cr", type:"bat", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/872.png" },
        { name: "P Nissanka ✈️", basePrice: "0.75cr", type:"bat", src:"https://statico.sportskeeda.com/editor/2024/08/deaae-17231953968406-1920.jpg" },
        { name: "Steve Smith ✈️", basePrice: "2cr", type:"bat", src:"https://images.mykhel.com//webp/images/cricket/players/2/4552.jpg" },
      ],
    },
    {
      setName: "SET 32 AL4",
      players: [
        { name: "Gus Atkinson ✈️", basePrice: "2cr", type:"al", src:"https://www.yolo247.co/sports/tournaments/wp-content/uploads/2024/01/Gus-Atkinson.png" },
        { name: "Tom Curran ✈️", basePrice: "2cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/309.png" },
        { name: "K Gowtham", basePrice: "1cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/179.png" },
        { name: "Mohammad Nabi ✈️", basePrice: "1.5cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/217.png" },
        { name: "Mitchell Santner ✈️", basePrice: "2cr", type:"al", src:"https://www.mumbaiindians.com/static-assets/images/players/large/57903.png?v=4.49&w=200" },
        { name: "Jayant Yadav", basePrice: "0.75cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/165.png" },
      ],
    },
    {
      setName: "SET 33 FA4",
      players: [
        { name: "Fazal Haq Farooqi ✈️", basePrice: "2cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/67927.png?v=6.73" },
        { name: "Matt Henry ✈️", basePrice: "2cr", type:"bowl", src:"https://www.lucknowsupergiants.in/static-assets/images/players/60544.png?v=12.55" },
        { name: "Alzari Joseph ✈️", basePrice: "2cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/229.png" },
        { name: "Kuldeep Sen", basePrice: "0.75cr", type:"bowl", src:"https://www.punjabkingsipl.in/static-assets/images/players/70402.png?v=6.16" },
        { name: "Reece Topley ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.mumbaiindians.com/static-assets/images/players/large/58101.png?v=4.49&w=200" },
        { name: "Lizaad Williams ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.mumbaiindians.com/static-assets/images/players/large/57823.png?v=4.49&w=200" },
      ],
    },
    {
      setName: "SET 34 BA5",
      players: [
        { name: "R Van Der Dussen ✈️", basePrice: "2cr", type:"bat", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/20619.png" },
        { name: "Will Young ✈️", basePrice: "1.25cr", type:"bat", src:"https://cricclubs.com/documentsRep/profilePics/b04bc1a7-9632-45e6-a790-a702c06fe468.png" },
        { name: "Najibullah Zadran ✈️", basePrice: "0.75cr", type:"bat", src:"https://d13ir53smqqeyp.cloudfront.net/fc-player-images/1327.png" },
        { name: "Ibrahim Zadran ✈️", basePrice: "0.75cr", type:"bat", src:"https://www.bdcrictime.com/_next/image?url=https%3A%2F%2Fapi.bdcrictime.com%2FProfile%2Fibrahim-zadran-08_10_2023.jpg&w=384&q=75" },
      ],
    },
    {
      setName: "SET 35 AL5",
      players: [
        { name: "Sean Abott ✈️", basePrice: "2cr", type:"al", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/942.png" },
        { name: "Jacob Bethell ✈️", basePrice: "1.25cr", type:"al", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/jacon.png?itok=Ss-rZBSk" },
        { name: "Sarfaraz Khan", basePrice: "0.75cr", type:"al", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/1564.png" },
        { name: "Kyle Mayers ✈️", basePrice: "1.5cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2024/726.png" },
        { name: "Mathew Short ✈️", basePrice: "0.75cr", type:"al", src:"https://www.punjabkingsipl.in/static-assets/images/players/63846.png?v=6.16" },
      ],
    },
    {
      setName: "SET 36 FA5",
      players: [
        { name: "Jason Behrendorff ✈️", basePrice: "1.5cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/4.png" },
        { name: "D Chameera ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.delhicapitals.in/static-assets/images/players/ipl/58065.png?v=1.62" },
        { name: "Nathan Ellis ✈️", basePrice: "1.25cr", type:"bowl", src:"https://www.punjabkingsipl.in/static-assets/images/players/70324.png?v=6.16" },
        { name: "Shamar Joseph ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.lucknowsupergiants.in/static-assets/images/players/101907.png?v=12.55" },
        { name: "Josh Little ✈️", basePrice: "0.75cr", type:"bowl", src:"https://www.gujarattitansipl.com/static-assets/images/players/66081.png?v=5.12" },
        { name: "Shivam Mavi", basePrice: "0.75cr", type:"bowl", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/3779.png" },
        { name: "Navdeep Saini", basePrice: "0.75cr", type:"bowl", src:"https://www.rajasthanroyals.com/static-assets/images/players/64448.png?v=6.73" },
      ],
    },
    {
      setName: "SET 37 AL6",
      players: [
        { name: "Charith Asalanka ✈️", basePrice: "0.75cr", type:"al", src:"https://i2.wp.com/crictoday.com/wp-content/uploads/2023/06/Charith-Asalanka.jpg?strip=info&w=518&ssl=1" },
        { name: "Michell Bracewell ✈️", basePrice: "1.5cr", type:"al", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/1465.png" },
        { name: "J Overton ✈️", basePrice: "1.5cr", type:"al", src:"https://d13ir53smqqeyp.cloudfront.net/fc-player-images/1585.png" },
        { name: "D Wellalage ✈️", basePrice: "0.75cr", type:"al", src:"https://www.bdcrictime.com/_next/image?url=https%3A%2F%2Fapi.bdcrictime.com%2FProfile%2Fdunith-wellalage-09_10_2023.jpg&w=384&q=75" },
      ],
    },
    {
      setName: "SET 38 FA6",
      players: [
        { name: "D Madhushanka ✈️", basePrice: "0.75cr", type:"bowl", src:"https://cricclubs.com/documentsRep/profilePics/d9fa8dd7-8a2b-45cb-bd6a-eb69d47b5674.jpeg" },
        { name: "Adam Milne ✈️", basePrice: "2cr", type:"bowl", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/434.png" },
        { name: "Lungi Nigdi ✈️", basePrice: "1cr", type:"bowl", src:"https://www.royalchallengers.com/PRRCB01/public/styles/s/public/2024-11/lungi%20%281%29.png?itok=LRyEdinz" },
        { name: "William U Rouke ✈️", basePrice: "1.5cr", type:"bowl", src:"https://images-cricketcom.imgix.net/players/74400_headshot_safari.png?auto=format,compress" },
      ],
    },
    {
      setName: "SET 39",
      players: [
        { name: "Jason Holdar ✈️", basePrice: "1cr", type:"al", src:"https://www.rajasthanroyals.com/static-assets/images/players/10232.png?v=6.73" },
        { name: "Shakib Al Hasan ✈️", basePrice: "1cr", type:"al", src:"https://www.lakriders.us/static-assets/images/players/3782.png?v=1.27" },
        { name: "Mahedi Hasan ✈️", basePrice: "1cr", type:"bowl", src:"https://cricclubs.com/documentsRep/profilePics/2777c265-a565-4ce2-a079-aadd732b8f2d.png" },
        { name: "Tim Southee ✈️", basePrice: "1.5cr", type:"bowl", src:"https://documents.iplt20.com/ipl/IPLHeadshot2023/77.png" },
      ],
    },
    {
      setName: "SET 40",
      players: [
        { name: "Ashton Agar ✈️", basePrice: "1.25cr", type:"bowl", src:"https://cricclubs.com/documentsRep/profilePics/d4e784d5-192b-4e6d-93a2-1af2beb2a9ee.png" },
        { name: "Chris Jordan ✈️", basePrice: "1.25cr", type:"al", src:"https://www.mumbaiindians.com/static-assets/images/players/large/action-shots/26718.png?v=4.16&w=400" },
        { name: "Kyle Jamison ✈️", basePrice: "1.5cr", type:"bowl", src:"https://images.mykhel.com//webp/images/cricket/players/6/7126.jpg" },
        { name: "James Neesham ✈️", basePrice: "1.25cr", type:"al", src:"https://assets.iplt20.com/ipl/IPLHeadshot2022/20615.png" },
      ],
    },
  ];

  export default playerData;
