
import React from "react";

const ListPage = () => {

const players = {
    Batsman: [
      { name: "Rohit Sharma", price: "2cr" },
      { name: "Virat Kohli", price: "2cr" },
      { name: "Suryakumar Yadav", price: "1.5cr" },
      { name: "Yashasvi Jaiswal", price: "1cr" },
      { name: "Rajat Patidar", price: "50L" },
      { name: "Tilak Varma", price: "1cr" },
      { name: "Shreyas Iyer", price: "1.5cr" },
      { name: "Ruturaj Gaikwad", price: "1cr" },
      { name: "Faf du Plessis", price: "2cr" },
      { name: "Shubman Gill", price: "1.5cr" },
      { name: "Travis Head", price: "1cr" },
      { name: "Pathum Nissanka", price: "50L" },
      { name: "Karun Nair", price: "50L" },
      { name: "Aiden Markram", price: "1.5cr" },
      { name: "Joe Root", price: "2cr" },
      { name: "Rinku Singh", price: "50L" },
      { name: "Dawid Warner", price: "2cr" },
      { name: "Babar Azam", price: "2cr" },
      { name: "Reeza Hendricks", price: "1cr" },
      { name: "Ibrahim Zadran", price: "50L" },
      { name: "Sarfaraz Khan", price: "50L" },
      { name: "Charith Asalanka", price: "1cr" },
      { name: "Fakhar Zaman", price: "1.5cr" },
      { name: "Steve Smith", price: "2cr" },
      { name: "David Miller", price: "1.5cr" },
      { name: "Temba Bavuma", price: "1cr" },
      { name: "Marnus Labuchagne", price: "1.5cr" },
      { name: "Kane Williamson", price: "2cr" },
      { name: "Saim Ayub", price: "50L" },
      { name: "Abdullah Shafique", price: "50L" },
      { name: "Usman Khawaja", price: "1.5cr" },
      { name: "Devdutt Padikkal", price: "1cr" },
      { name: "Jacob Bethell", price: "50L" },
      { name: "Jake Frasor McGurk", price: "50L" },
      { name: "Sameer Rizwi", price: "50L" },
      { name: "Ashutosh Sharma", price: "50L" },
      { name: "Abdul Samad", price: "50L" },
    ],
    Bowler: [
      { name: "Khaleel Ahmed", price: "1cr" },
      { name: "Jasprit Bumrah", price: "2cr" },
      { name: "Nathon Lyon", price: "1.5cr" },
      { name: "Adil Rashid", price: "1.5cr" },
      { name: "Umran Malik", price: "1cr" },
      { name: "Dilshan Madhushanka", price: "1cr" },
      { name: "Lokie Ferguson", price: "1.5cr" },
      { name: "Avesh Khan", price: "1cr" },
      { name: "Jofra Archer", price: "2cr" },
      { name: "Mitchell Starc", price: "2cr" },
      { name: "Matt Henry", price: "1.5cr" },
      { name: "Mustafizur Rahman", price: "1cr" },
      { name: "William U Rouke", price: "50L" },
      { name: "Abbas Afridi", price: "50L" },
      { name: "M Pathirana", price: "50L" },
      { name: "Akash Deep", price: "50L" },
      { name: "Md Siraj", price: "1.5cr" },
      { name: "Mohit Sharma", price: "50L" },
      { name: "Adam Zampa", price: "1.5cr" },
      { name: "Mohammad Shami", price: "2cr" },
      { name: "Nathan Ellis", price: "50L" },
      { name: "Alzari Joseph", price: "1cr" },
      { name: "Reece Topley", price: "1.5cr" },
      { name: "Sandeep Sharma", price: "50L" },
      { name: "Jaydev Unadket", price: "1cr" },
      { name: "Yuzvendra Chahal", price: "1.5cr" },
      { name: "Taskin Ahmed", price: "50L" },
      { name: "Shaheen Afridi", price: "2cr" },
      { name: "Trent Boult", price: "2cr" },
      { name: "Tim Southee", price: "1.5cr" },
      { name: "Anrich Nortje", price: "1.5cr" },
      { name: "Kagiso Rabada", price: "2cr" },
      { name: "T Natrajan", price: "1cr" },
      { name: "Fazal Haq Farooqi", price: "50L" },
      { name: "Ish Sodhi", price: "1cr" },
      { name: "Naseem Shah", price: "1.5cr" },
      { name: "Akeal Hosein", price: "50L" },
      { name: "Maheesh Theekshana", price: "1.5cr" },
      { name: "Ravi Bishnoi", price: "1.5cr" },
      { name: "Arshdeep Singh", price: "1cr" },
      { name: "Josh Hazlewood", price: "1.5cr" },
      { name: "Naveen Ul Haq", price: "50L" },
      { name: "Mahedi Hasan", price: "50L" },
      { name: "Keshav Maharaj", price: "50L" },
      { name: "Haris Rauf", price: "1.5cr" },
      { name: "Varun Chakravarthy", price: "1cr" },
      { name: "Tabraiz Shamsi", price: "50L" },
      { name: "Mujeeb Ur Rahman", price: "1.5cr" },
      { name: "Kuldeep Yadav", price: "2cr" },
      { name: "Romario Shepherd", price: "50L" },
      { name: "Nuwan Tushara", price: "50L" },
      { name: "Michael Bracewell", price: "50L" },
      { name: "Pat Cummins", price: "2cr" },
      { name: "Ashton Agar", price: "50L" },
      { name: "Lungi Nigdi", price: "50L" },
      { name: "Chris Woakes", price: "1.5cr" },
      { name: "Mohd Nawaz", price: "1cr" },
      { name: "Shardul Thakur", price: "1.5cr" },
      { name: "Bhuvneshwar Kumar", price: "1.5cr" },
      { name: "Yash Dayal", price: "50L" },
      { name: "Kyle Jamison", price: "50L" },
      { name: "Azaz Patel", price: "50L" },
      { name: "Swapnil Singh", price: "50L" },
      { name: "Mukesh Kumar", price: "1cr" },
      { name: "Prasidh Krishna", price: "1.5cr" },
      { name: "Ishant Sharma", price: "1cr" },
      { name: "Harshit Rana", price: "50L" },
      { name: "Mayank yadav", price: "50L" },
      { name: "Deepak Chahar", price: "1cr" },
      { name: "Rahul Chahar", price: "50L" },
      { name: "Harshal Patel", price: "50L" },
      { name: "Jamie Anderson", price: "1.5cr" },
    ],
    AllRounder: [
      { name: "Ravindra Jadeja", price: "2cr" },
      { name: "Hardik Pandya", price: "2cr" },
      { name: "Sunil Narine", price: "1.5cr" },
      { name: "Moeen Ali", price: "1.5cr" },
      { name: "Vijay Shankar", price: "1cr" },
      { name: "Cameron Green", price: "2cr" },
      { name: "Liam Livingstone", price: "1.5cr" },
      { name: "Sam Curran", price: "1.5cr" },
      { name: "Rahul Tewatia", price: "1cr" },
      { name: "Krishnappa Gowtham", price: "1cr" },
      { name: "Krunal Pandya", price: "1.5cr" },
      { name: "Marcus Stoinis", price: "1.5cr" },
      { name: "Washington Sundar", price: "1cr" },
      { name: "Andre Russell", price: "2cr" },
      { name: "Mitchell Marsh", price: "2cr" },
      { name: "Wanindu Hasaranga", price: "1.5cr" },
      { name: "Shakib Al Hasan", price: "2cr" },
      { name: "Roston Chase", price: "1cr" },
      { name: "Dhananjaya De Silva", price: "1cr" },
      { name: "Imad Wasim", price: "1cr" },
      { name: "Marco Jansen", price: "1.5cr" },
      { name: "Rachin Ravindra", price: "50L" },
      { name: "Axar Patel", price: "1.5cr" },
      { name: "Rovman Powell", price: "1cr" },
      { name: "Glenn Maxwell", price: "2cr" },
      { name: "Daryl Mitchell", price: "1cr" },
      { name: "Will Young", price: "50L" },
      { name: "Sherfane Rutherford", price: "50L" },
      { name: "Azmatullah Omarzai", price: "50L" },
      { name: "Ben Stokes", price: "2cr" },
      { name: "Mohammad Nabi", price: "1cr" },
      { name: "Rashid Khan", price: "2cr" },
      { name: "Mitchell Santner", price: "1.5cr" },
      { name: "Ravichandran Ashwin", price: "1.5cr" },
      { name: "Jason Holder", price: "1.5cr" },
      { name: "Shivam Sube", price: "50L" },
      { name: "Nitish Kumar Reddy", price: "50L" },
      { name: "Chris Jordan", price: "1.5cr" },
      { name: "Abhishek Sharma", price: "50L" },
      { name: "Gerald Coetzee", price: "50L" },
      { name: "Mark Chapman", price: "50L" },
      { name: "Tim David", price: "50L" },
      { name: "Deepak Hooda", price: "1cr" },
      { name: "Mahipal Lomror", price: "50L" },
      { name: "Venketesh Iyer", price: "50L" },
      { name: "Will Jacks", price: "50L" },
      { name: "Karn Sharma", price: "50L" },
      { name: "Riyan Parag", price: "50L" },
      { name: "Nitesh Rana", price: "1cr" },
    ],
    Wicketkeepers: [
      { name: "Josh Inglis", price: "1.5cr" },
      { name: "Sanju Samson", price: "2cr" },
      { name: "Jitesh Sharma", price: "1.5cr" },
      { name: "Md Rizwan", price: "1.5cr" },
      { name: "Shai Hope", price: "1cr" },
      { name: "Jonny Bairstow", price: "2cr" },
      { name: "Dhruv Jurel", price: "50L" },
      { name: "Phil Salt", price: "50L" },
      { name: "Harry Brook", price: "1cr" },
      { name: "Nicholas Pooran", price: "2cr" },
      { name: "Devon Conway", price: "2cr" },
      { name: "Jos Buttler", price: "2cr" },
      { name: "Rishabh Pant", price: "2cr" },
      { name: "KL Rahul", price: "2cr" },
      { name: "Quinton De Kock", price: "2cr" },
      { name: "Alex Carey", price: "1.5cr" },
      { name: "KS Bharat", price: "1cr" },
      { name: "Abhishek Porel", price: "50L" },
      { name: "Kusal Mendis", price: "1.5cr" },
      { name: "Rahmanullah Gurbaz", price: "1cr" },
      { name: "Glenn Phillips", price: "1.5cr" },
      { name: "Finn Allen", price: "50L" },
      { name: "Tristan Stubbs", price: "50L" },
      { name: "Henrich Klassen", price: "50L" },
      { name: "Ishan Kishan", price: "1.5cr" },
      { name: "Anuj Rawat", price: "50L" },
      { name: "Shimron Hetmyer", price: "50L" },
    ],
  };
  
  

  return (
  
    <div className="p-6">
  <h1 className="text-2xl font-bold mb-6">Player List with Base Prices</h1>
  <div className="space-y-6">
    {Object.keys(players).map((category) => (
      <div key={category} className="bg-gray-100 p-4 rounded shadow">
        <h2 className="text-xl font-semibold mb-3">{category}</h2>
        <ul className="space-y-2">
          {players[category].map((player, index) => (
            <li
              key={index}
              className="flex justify-between bg-white p-3 rounded shadow"
            >
              <span className="mr-3">{index + 1}.</span> {/* Display serial number */}
              <span>{player.name}</span>
              <span className="text-gray-700">
                ₹{player.price.toLocaleString()}
              </span>
            </li>
          ))}
        </ul>
      </div>
    ))}
  </div>
</div>

  );
};

export default ListPage;
